name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: ["hipsycl+cuda"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag luigicrisci/hipsycl_cuda10.2:latest
    - name: Push image
      run: docker image push luigicrisci/hipsycl_cuda10.2_llvm11:latest
